version: '3.4'
# https://www.digitalocean.com/community/tutorials/containerizing-a-ruby-on-rails-application-for-development-with-docker-compose-es

services:

  # Still not working properly. Only database container is used
  app:
    # user: ${USER}
    build:
      context: .      
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app
      # These two directories are container-specific, must not polute host
      # Some gems and modules can be compiled and different from host
      - gem_cache:/usr/local/bundle/gems
      - gems:/usr/local/bundle/ruby/2.6.0
      - node_modules:/app/node_modules
      # Directorio para las gemas?
    env_file: .env
    environment:
      RAILS_ENV: development
      # HOST_USER: ${user}

  database:
    image: postgres:12.1
    # Temporary
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  gem_cache:
  gems:
  node_modules:
      